"use client";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "../../../../urohealth//app/globals.css";

//import font family
import { Poppins } from "next/font/google";
import { Josefin_Sans } from "next/font/google";

import { Toaster } from "react-hot-toast";
import Providers from "../Provider";
import { SessionProvider } from "next-auth/react";
import React, { FC } from "react";
import { useLoadUserQuery } from "@/redux/features/api/apiSlice";
import Loader from "../../app/component/Loader/Loader";

import Footer from "../service/home/Footer"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Poppins",
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Josefin",
});

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers>
      
          <Custom>{children}</Custom>
          <Toaster position="top-center" reverseOrder={false} />
      
      </Providers>
    </>
  );
}

const Custom: FC<{ children: React.ReactNode }> = ({ children }) => {
  const { isLoading } = useLoadUserQuery({});

  return (
    <>
      {isLoading ? (
        <Loader />
      ) : (
        <>
          <div className="mt-19">{children}</div>
          <Footer />
        </>
      )}
    </>
  );
};
